name: SimpleAutoMessage
main: com.carlgo11.simpleautomessage.Main
version: ${project.version}
description: Auto-announcer plugin
author: Carlgo11
website: http://www.carlgo11.com/
commands:
   simpleautomessage:
     aliases: [automessage, simplemsg, automsg]
     description: Main command of SimpleAutoMessage.
     
permissions:
  simpleautomessage.seemsg:
    default: true
    description: Permission to see the messages broadcasted by SimpleAutomessage
  simpleautomessage.simpleautomessage:
    default: true
    description: Permission to use /simpleautomessage 
  simpleautomessage.simpleautomessage.reload:
    default: op
    description: Permission to use /simpleautomessage reload
  simpleautomessage.simpleautomessage.list:
    default: op
    description: Permission to use /simpleautomessage reload
  simpleautomessage.simpleautomessage.update:
    default: op
    description: Permission to use /simpleautomessage update
  simpleautomessage.notify:
    defaylt: op
    description: Player will be notified on login when a new update is avible.
  simpleautomessage.*:
    default: op
    description: Gives the player all the SimpleAutoMessage permissions