name: SimpleAutoMessage
main: com.carlgo11.simpleautomessage.Main
version: 1.2.1
description: Auto-announcer plugin
author: Carlgo11
website: http://www.carlgo11.com/
commands:
   simpleautomessage:
     aliases: [automessage, simplemsg, automsg]
     description: Main command of SimpleAutoMessage.
     
permissions:
  simpleautomessage.seemsg:
    default: true
    description: Permission to see the messages broadcasted by SimpleAutomessage
  simpleautomessage.simpleautomessage:
    default: true
    description: Permission to use /simpleautomessage 
  simpleautomessage.simpleautomessage.reload:
    default: op
    description: Permission to use /simpleautomessage reload
  simpleautomessage.simpleautomessage.list:
    default: op
    description: Permission to use /simpleautomessage reload
  simpleautomessage.simpleautomessage.update:
    default: op
    description: Permission to use /simpleautomessage update
  simpleautomessage.simpleautomessage.support:
    default: op
    description: Permission to use /simpleautomessage support
  simpleautomessage.simpleautomessage.report:
    default: op
    description: Permission to use /simpleautomessage report
  simpleautomessage.notify:
    defaylt: op
    description: Player will be notified on login when a new update is avible.
  simpleautomessage.*:
    default: op
    description: Gives the player all the SimpleAutoMessage permissions
    children:
      simpleautomessage.simpleautomessage: true
      simpleautomessage.simpleautomessage.reload: true
      simpleautomessage.simpleautomessage.list: true
      simpleautomessage.simpleautomessage.update: true
      simpleautomessage.simpleautomessage.support: true
      simpleautomessage.simpleautomessage.report: true
      simpleautomessage.seemsg: true
      simpleautomessage.notify: true