name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload
      run: mvn deploy -Dregistry=https://maven.pkg.github.com/Carlgo11 -Dtoken=GH_TOKEN
    - uses: actions/upload-artifact@v2
      with:
        path: target/*.jar
